xpcall(function()
  term.clear()
  
  local button = require(".lib.ui.button")
  local events = require(".lib.events")
  local manager = events:new()
  local buttonEventManager = button.eventManager:new()
  local newButton = button:new(3, 3, "Hello World", function()
    term.setCursorPos(30, 1)
  end)
  newButton:render()
  buttonEventManager:add(newButton)

  buttonEventManager:inject(manager)
  events:listen()
end, function(err)
  print(err)
  print(debug.traceback())
end)